[2022-07-13 09:06:42,643] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v2.second_task manual__2022-07-13T09:04:40.025375+00:00 [queued]>
[2022-07-13 09:06:42,666] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag_v2.second_task manual__2022-07-13T09:04:40.025375+00:00 [queued]>
[2022-07-13 09:06:42,667] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-13 09:06:42,668] {taskinstance.py:1377} INFO - Starting attempt 2 of 6
[2022-07-13 09:06:42,669] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-13 09:06:42,695] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): second_task> on 2022-07-13 09:04:40.025375+00:00
[2022-07-13 09:06:42,705] {standard_task_runner.py:52} INFO - Started process 1257 to run task
[2022-07-13 09:06:42,709] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v2', 'second_task', 'manual__2022-07-13T09:04:40.025375+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpnziqmuhn', '--error-file', '/tmp/tmptsyvsy0c']
[2022-07-13 09:06:42,712] {standard_task_runner.py:80} INFO - Job 10: Subtask second_task
[2022-07-13 09:06:42,811] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag_v2.second_task manual__2022-07-13T09:04:40.025375+00:00 [running]> on host 8e2218deeaf2
[2022-07-13 09:06:42,912] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=harshab
AIRFLOW_CTX_DAG_ID=our_first_dag_v2
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2022-07-13T09:04:40.025375+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-13T09:04:40.025375+00:00
[2022-07-13 09:06:42,916] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-13 09:06:42,918] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo I am the second task']
[2022-07-13 09:06:42,931] {subprocess.py:85} INFO - Output:
[2022-07-13 09:06:42,934] {subprocess.py:92} INFO - I am the second task
[2022-07-13 09:06:42,936] {subprocess.py:96} INFO - Command exited with return code 0
[2022-07-13 09:06:42,982] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v2, task_id=second_task, execution_date=20220713T090440, start_date=20220713T090642, end_date=20220713T090642
[2022-07-13 09:06:43,047] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-13 09:06:43,100] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
